name: Supabase

run-name: Supabase - ${{ github.event.head_commit.message || 'Manual Run' }}

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}

    steps:
      - name: Disabled Notice
        run: echo "Supabase deploy action is currently disabled."

      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link to Supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Commit File Changes
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Update Supabase Types
          branch: ${{ github.head_ref }}
          file_pattern: |
            shared/types/supabase.ts

      - name: Push database migrations
        run: supabase db push

      - name: Deploy Edge Functions
        run: |
          if [ -d supabase/functions ] && [ "$(ls -A supabase/functions)" ]; then
            supabase functions deploy --project-ref $SUPABASE_PROJECT_ID
          else
            echo "No Edge Functions to deploy."
          fi

      - name: Generate Supabase types
        run: |
          supabase gen types typescript --project-id "$SUPABASE_PROJECT_ID" --debug > shared/types/supabase.ts
